# Generated by Django 2.2.10 on 2020-05-27 14:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20200526_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=70),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=17, validators=[django.core.validators.RegexValidator(message="Формат: '+999999999'.", regex='^\\+?1?\\d{9,15}$')]),
        ),
    ]
