# Generated by Django 2.2.5 on 2020-04-13 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200413_1801'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('articul', models.CharField(default='00000000', max_length=16)),
                ('size', models.CharField(max_length=45, null=True)),
                ('material', models.CharField(max_length=30, null=True)),
                ('price', models.IntegerField()),
                ('quantity', models.IntegerField(null=True)),
                ('subCategory', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.SubCategory')),
            ],
        ),
    ]
