# Generated by Django 2.2.5 on 2020-04-13 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_auto_20200413_1843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.AddField(
            model_name='product',
            name='image0',
            field=models.ImageField(blank=True, upload_to='media/images/', verbose_name='Главное изображение'),
        ),
        migrations.AddField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, upload_to='media/images/', verbose_name='Доп Изображение 1'),
        ),
        migrations.AddField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='media/images/', verbose_name='Доп Изображение 2'),
        ),
        migrations.AddField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, upload_to='media/images/', verbose_name='Доп Изображение 3'),
        ),
    ]
