# Generated by Django 2.2.10 on 2020-04-27 06:57

from django.db import migrations
from django.contrib.postgres.operations import UnaccentExtension


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_auto_20200416_2314'),
    ]

    operations = [
         UnaccentExtension()
    ]