# Generated by Django 2.2.10 on 2020-05-23 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_auto_20200427_1357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image0',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image1',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Доп Изображение 1'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image2',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Доп Изображение 2'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image3',
            field=models.ImageField(blank=True, upload_to='images/', verbose_name='Доп Изображение 3'),
        ),
    ]
