# Generated by Django 2.2.10 on 2020-05-26 16:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_auto_20200526_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='description',
            new_name='text',
        ),
    ]
