# Generated by Django 2.2.10 on 2020-05-31 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0020_auto_20200527_1450'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='quantity',
        ),
    ]
