# Generated by Django 2.2.10 on 2020-05-26 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping_cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказы', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'Транзакции', 'verbose_name_plural': 'Транзакции'},
        ),
    ]
